### ISSUE TITLE
Score tracker 🏆

### ISSUE THREAD

**Issue by Langorithm** [GonzaFerretti/roll-or-die#2]
Ways to show progress over runs

- [ ] Qty of enemies killed
  - [ ] Update record on enemy death
- [ ] Seconds until death
---
- [ ] Show progress:
- Upon game over
**and/or**
- Continously over the run
